fix: remove commit branch check for now

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,27 +23,27 @@ jobs:
           echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
 
   # Just in case we accidentally release something not on main.
-  commit-branch-check:
-    name: "Check commit branch"
-    runs-on: "ubuntu-latest"
-    needs:
-      - "crate-info"
+  # commit-branch-check:
+  #   name: "Check commit branch"
+  #   runs-on: "ubuntu-latest"
+  #   needs:
+  #     - "crate-info"
 
-    steps:
-      - name: "Checkout source code"
-        uses: "actions/checkout@v3"
-        with:
-          fetch-depth: 0
+  #   steps:
+  #     - name: "Checkout source code"
+  #       uses: "actions/checkout@v3"
+  #       with:
+  #         fetch-depth: 0
 
-      - name: "Check if commit is on main"
-        run: |
-          COMMIT_HASH=$(git log -1 --format=%H ${{ github.ref }})
-          GREP_OUTPUT=$(git log origin/main --format=%H | grep "$COMMIT_HASH")
+  #     - name: "Check if commit is on main"
+  #       run: |
+  #         COMMIT_HASH=$(git log -1 --format=%H ${{ github.ref }})
+  #         GREP_OUTPUT=$(git log origin/main --format=%H | grep "$COMMIT_HASH")
 
-          if [ -z "$GREP_OUTPUT" ]; then
-            echo "Cannot release commits not on the main branch"
-            exit 1
-          fi
+  #         if [ -z "$GREP_OUTPUT" ]; then
+  #           echo "Cannot release commits not on the main branch"
+  #           exit 1
+  #         fi
 
   crate-version-check:
     name: "Check crate version"
@@ -69,7 +69,6 @@ jobs:
     runs-on: "ubuntu-latest"
     needs:
       - "crate-info"
-      - "commit-branch-check"
       - "crate-version-check"
     outputs:
       release-id: ${{ steps.create.outputs.id }}
@@ -90,7 +89,6 @@ jobs:
     needs:
       - "crate-info"
       - "draft-release"
-      - "commit-branch-check"
       - "crate-version-check"
 
     strategy:
@@ -173,7 +171,6 @@ jobs:
     needs:
       - "crate-info"
       - "draft-release"
-      - "commit-branch-check"
       - "crate-version-check"
 
     strategy:
